// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwHpElIPjJ6pLCfIYe7clQZbVz-7kZ5Ds',
    appId: '1:175908739531:web:423476d1a86eda39123e4e',
    messagingSenderId: '175908739531',
    projectId: 'captalis-88b24',
    authDomain: 'captalis-88b24.firebaseapp.com',
    storageBucket: 'captalis-88b24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvm7ujTw5cMEQslmHaibxGC81-7OVxcG4',
    appId: '1:175908739531:android:dc21eff12410782a123e4e',
    messagingSenderId: '175908739531',
    projectId: 'captalis-88b24',
    storageBucket: 'captalis-88b24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQXy0JdQMclh2z234nDg7pB8Myx4UpsBk',
    appId: '1:175908739531:ios:f24091513338c08e123e4e',
    messagingSenderId: '175908739531',
    projectId: 'captalis-88b24',
    storageBucket: 'captalis-88b24.firebasestorage.app',
    iosBundleId: 'com.example.captalis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQXy0JdQMclh2z234nDg7pB8Myx4UpsBk',
    appId: '1:175908739531:ios:f24091513338c08e123e4e',
    messagingSenderId: '175908739531',
    projectId: 'captalis-88b24',
    storageBucket: 'captalis-88b24.firebasestorage.app',
    iosBundleId: 'com.example.captalis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwHpElIPjJ6pLCfIYe7clQZbVz-7kZ5Ds',
    appId: '1:175908739531:web:7914a7e5bdfcebda123e4e',
    messagingSenderId: '175908739531',
    projectId: 'captalis-88b24',
    authDomain: 'captalis-88b24.firebaseapp.com',
    storageBucket: 'captalis-88b24.firebasestorage.app',
  );
}
